[package]
name = "egui_xml"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { version = "*", path = "parser" }
macros = { version = "*", path = "macros" }
egui_extras = "0.27"

[dev-dependencies]
eframe = "0.27"
egui = "0.27"

[[example]]
name = "simple"

[[example]]
name = "file"
