[package]
name = "egui_form"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "parser" }
macros = { path = "macros" }
egui_extras = "0.22.0"

[dev-dependencies]
eframe = "0.22.0"
egui = "0.22.0"

[[example]]
name = "simple"

[[example]]
name = "file"
