[package]
name = "egui_form"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "parser" }
macros = { path = "macros" }

[dev-dependencies]
egui = "0.22.0"
eframe = "0.22.0"
egui_extras = "0.22.0"


[[example]]
name = "simple"
