[package]
name = "egui_xml_parser"
version = "0.1.2"
edition = "2021"
description = "A parser for crate egui_xml"
license = "MIT"
github = "https://github.com/GodGotzi/egui_xml/tree/main/parser"

[dependencies]
quick-xml = "0.31.0"
proc-macro2 = "1.0"
quote = "1.0"
