name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build example simple
      run: cargo build --example simple
    - name: Build example file
      run: cargo build --example file
    - name: Run tests
      run: cargo test --verbose
